### PR TITLE
api/vessel reports

### PR DESCRIPTION
**Pull request by Swapna-Sahu**
Created new PR for the vessel report api because Zaki has renamed the column position to position_waypoints

### CODE REVIEW

**Comment by ghost** [comment]
OMG

**Review by ghost — APPROVED** [review]
It seems OK.

**Comment by zkwsk** [comment]
@Swapna-Sahu need to resolve your conflicts :)

**Comment by Swapna-Sahu** [comment]
resolved my conflicts

**Comment by zkwsk** [comment]
I  don't see a commit here, so I think you forgot a step?

Further, if I run your branch now "get vessel reports by vessel ID" works, but create vessel report seems to be broken 😭

**Comment by zkwsk** [comment]
Look at #70

**Pull request closed without merging**
