### PR TITLE
Feature/vessels-ui

### PR DESCRIPTION
**Pull request by Swapna-Sahu**
With ref to https://github.com/HackYourFuture-CPH/ov-class09-fp/pull/65

### CODE REVIEW

**Comment by Swapna-Sahu** [comment]
https://github.com/HackYourFuture-CPH/ov-class09-fp/pull/65

**Comment by lil2400** [comment]
You have lot of changes that is not really neccesarly to go with this push.  
Fallow the Zaki's comment here https://github.com/HackYourFuture-CPH/ov-class09-fp/pull/67#issuecomment-534499090 how to fix that.

**Note that when you'll run git

>  cherry-pick your_sha

 make sure you put your commited sha.**

**Comment by zkwsk** [comment]
Thanks @lil2400 for sharing that. The situation is actually not quite the same is with your PR. As far as I can see all of her commits are related to vessels UI. We just had a lot of review rounds.

On your PR you had a bunch of changes that I made that had nothing to do with what you where fixing, so that's an indication that you branched out from one place and then tries to branch into a different place than where it came from.

Here we just had a lot of review rounds and @Swapna-Sahu had to merge develop into her branch many times along the way, which is normal. Some times :D

**Review by zkwsk — APPROVED** [review]
Great work ✌️Guess this is our first real component in Storybook, then?

**Pull request merged**
